In [ ]:
!pip install chromadb sentence-transformers --quiet
print("Installation complete!")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 72.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 106.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 82.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the 

In [ ]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import chromadb

print("All libraries imported successfully!")
print(f"ChromaDB version: {chromadb.__version__}")

All libraries imported successfully!
ChromaDB version: 1.5.9


In [ ]:
doucments = [
    "ETL is used to clean and transform data",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles",
    "SQL is used to query databases",
    "Machine learning trains models on data"
]

query_keyword = "vehicle"
print(f"KEYWORD SEARCH for:'{query_keyword}'")
print("="*60)

for i , doc in enumerate(doucments):
  if query_keyword.lower() in doc.lower():
    print(f"FOUND \t\t[ doc_{i}]\t\t\t:{doc}")
  else:
    print(f"NOT FOUND \t[ doc_{i}]\t\t\t:{doc}")
print()
print("PROBLEM: doc_2 talks about 'Cars and trucks'- which ARE vehicles! ")
print("but keyword search MISSED it because it searched for the exact word 'vehicle'")

KEYWORD SEARCH for:'vehicle'
NOT FOUND 	[ doc_0]			:ETL is used to clean and transform data
FOUND 		[ doc_1]			:A vehicle is a mode of transportation
NOT FOUND 	[ doc_2]			:Cars and trucks are popular automobiles
NOT FOUND 	[ doc_3]			:SQL is used to query databases
NOT FOUND 	[ doc_4]			:Machine learning trains models on data

PROBLEM: doc_2 talks about 'Cars and trucks'- which ARE vehicles! 
but keyword search MISSED it because it searched for the exact word 'vehicle'


In [ ]:
model=SentenceTransformer('all-MiniLM-L6-v2')


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
sentence="ETL is used to clean and transform data"
embedding=model.encode(sentence)



In [ ]:
print(embedding.min(),embedding.max())

-0.13814422 0.18147615


In [ ]:
sentences = [
    "ETL is used to clean and transform data",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles",
    "SQL is used to query databases",
    "Machine learning trains models on data"
]
embedding1=model.encode(sentences)

print(len(sentences),embedding1.shape,embedding1[:10].round(4),embedding1.min(),embedding1.max())

5 (5, 384) [[-0.0784  0.0541  0.0224 ...  0.0011  0.0316  0.0009]
 [-0.005  -0.0067  0.0068 ...  0.0669  0.0594 -0.0416]
 [ 0.0925 -0.0383  0.0287 ...  0.0212  0.092   0.0369]
 [ 0.0298 -0.0137 -0.0951 ...  0.0411  0.0983 -0.0323]
 [-0.0604 -0.1063  0.0693 ... -0.0024 -0.0141 -0.041 ]] -0.21012594 0.18147615


In [ ]:
def cosine_similarity(vec_a,vec_b):
  dot_product=np.dot(vec_a,vec_b)
  norm_a=np.linalg.norm(vec_a)
  norm_b=np.linalg.norm(vec_b)
  return dot_product/(norm_a*norm_b)

sin_01=cosine_similarity(embedding1[0],embedding1[1])
sin_02=cosine_similarity(embedding1[0],embedding1[2])
sin_12=cosine_similarity(embedding1[1],embedding1[2])


print(f"Sentence 0:'{sentence[0]}'")
print(f"Sentence 1:'{sentence[1]}'")
print(f"Sentence 2:'{sentence[2]}'")
print(f"Similarity(0,1):{sin_01:.4f}")
print(f"Similarity(0,2):{sin_02:.4f}")
print(f"Similarity(1,2):{sin_12:.4f}")
5

Sentence 0:'E'
Sentence 1:'T'
Sentence 2:'L'
Similarity(0,1):0.1663
Similarity(0,2):0.0757
Similarity(1,2):0.5384
